modifier_demonologist_riual_of_summoning_status_effect = class({})

function modifier_demonologist_riual_of_summoning_status_effect:GetAttributes()
	return MODIFIER_ATTRIBUTE_PERMANENT + MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE 
end

function modifier_demonologist_riual_of_summoning_status_effect:IsHidden()
	return true
end

function modifier_demonologist_riual_of_summoning_status_effect:IsPurgable()
	return false
end

function modifier_demonologist_riual_of_summoning_status_effect:RemoveOnDeath()
	return false
end

function modifier_demonologist_riual_of_summoning_status_effect:GetStatusEffectName()
	return "particles/custom/demonologist/lia_demonologist_ritual_of_summoning.vpcf"
end

function modifier_demonologist_riual_of_summoning_status_effect:StatusEffectPriority()
	return 30
end